server:
  port: ${my-config.server.port}
spring:
  application:
    name: web-eureka
  profiles:
    active: dev
eureka:
  server:
    eviction-interval-timer-in-ms: ${my-config.eureka.server.refreshInterval}
    enable-self-preservation: false
  client:
    service-url:
      defaultZone: http://${my-config.eureka.instance.hostname}:8000/eureka/

    register-with-eureka: false
    fetch-registry: false

